baseURL = 'https://linetonthat.github.io'
languageCode = 'en-us'
title = 'Line Ton That'
theme= "PaperMod"
#theme = "tale"

#[[menu.main]]
#identifier = "example"
#name = "gallery"
#url = "https://example.org"
#weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 30
